gpus: 1
precision: 32
max_epochs: -1
max_steps: 200000
sync_batchnorm: false
log_every_n_steps:       500             #help='print/disp/save frequency'
resume_from_checkpoint:  null            #help='path to latest checkpoint'
strategy:                dp              #help='lightning accelerator'
val_check_interval:      0.1             #help=How often to check the validation set.
limit_val_batches:       0.1
accumulate_grad_batches: 1               #help='number of accumulated batches'
